/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.100
 * Generated at: 2025-03-25 01:35:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.bbs;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.yong.bbs.*;

public final class bbsContent_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1740636672021L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1742775571057L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.yong.bbs");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      com.yong.bbs.BbsDAO bdao = null;
      synchronized (session) {
        bdao = (com.yong.bbs.BbsDAO) _jspx_page_context.getAttribute("bdao", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (bdao == null){
          bdao = new com.yong.bbs.BbsDAO();
          _jspx_page_context.setAttribute("bdao", bdao, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\r');
      out.write('\n');

String idx_s = request.getParameter("idx");
if (idx_s == null || idx_s.equals("")) {
	idx_s = "0";
}
int idx = Integer.parseInt(idx_s);

BbsDTO dto = bdao.bbsContent(idx);

if (dto == null) {

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	window.alert('삭제된 게시글 또는 잘못된 접근입니다.');\r\n");
      out.write("	location.href = \"bbsList.jsp\";\r\n");
      out.write("</script>\r\n");

return;
}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/mainLayout.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');
      com.yong.member.MemberDAO mdao = null;
      mdao = (com.yong.member.MemberDAO) _jspx_page_context.getAttribute("mdao", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (mdao == null){
        mdao = new com.yong.member.MemberDAO();
        _jspx_page_context.setAttribute("mdao", mdao, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("\r\n");
      out.write("<!-- 상단으로 구분 -->\r\n");
      out.write("<script>\r\n");
      out.write("	function openLogin() {\r\n");
      out.write("		window\r\n");
      out.write("				.open('/myweb/member/login.jsp', 'login',\r\n");
      out.write("						'width=450 ,height=350');\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");

String sname = (String) session.getAttribute("sname");

      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("	");

	if (sname == null) {
	
      out.write("\r\n");
      out.write("	<div>\r\n");
      out.write("		<a href=\"javascript:openLogin()\">로그인</a>| <a href=\"/myweb/member/memberJoin.jsp\">회원가입</a>\r\n");
      out.write("	</div>\r\n");
      out.write("	");

	} else {
	
      out.write("\r\n");
      out.write("	<div>");
      out.print(sname);
      out.write("님 로그인중... | <a href=\"/myweb/member/logout.jsp\">로그아웃</a>\r\n");
      out.write("	</div>\r\n");
      out.write("	");

	}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<h1>JSP Study Site</h1>\r\n");
      out.write("	<!-- 메뉴 영역으로 구분 -->\r\n");
      out.write("	<nav>\r\n");
      out.write("		<ul>\r\n");
      out.write("			<li><a href=\"/myweb/index.jsp\">Home</a></li>\r\n");
      out.write("			<li><a href=\"/myweb/profile.jsp\">Profile</a></li>\r\n");
      out.write("			<li><a href=\"/myweb/bbs/bbsList.jsp\">자유게시판</a></li>\r\n");
      out.write("			<li><a href=\"/myweb/webfolder/webfolder.jsp\">yong드라이브</a></li>\r\n");
      out.write("			<li><a href=\"#\">방명록</a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</nav>\r\n");
      out.write("	<hr>\r\n");
      out.write("</header>");
      out.write("\r\n");
      out.write("	<section>\r\n");
      out.write("		<article>\r\n");
      out.write("			<h2>자유게시판 본문보기</h2>\r\n");
      out.write("			<fieldset>\r\n");
      out.write("				<legend>본문내용</legend>\r\n");
      out.write("				<table width=\"550\" border=\"1\" cellspacing=\"0\">\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>번호</th>\r\n");
      out.write("						<td>");
      out.print(dto.getIdx());
      out.write("</td>\r\n");
      out.write("						<th>작성날짜</th>\r\n");
      out.write("						<td>");
      out.print(dto.getWritedate());
      out.write("</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>작성자</th>\r\n");
      out.write("						<td>");
      out.print(dto.getWriter());
      out.write("</td>\r\n");
      out.write("						<th>조회수</th>\r\n");
      out.write("						<td>");
      out.print(dto.getReadnum());
      out.write("</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>제목</th>\r\n");
      out.write("						<td colspan=\"3\">");
      out.print(dto.getTitle());
      out.write("</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr height=\"150\">\r\n");
      out.write("						<td colspan=\"4\" align=\"left\" valign=\"top\">");
      out.print(dto.getContent().replaceAll("\n", "<br>"));
      out.write("</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td colspan=\"4\" align=\"center\">목록으로 | <a href=\"bbsReWrite.jsp?title=");
      out.print(dto.getTitle());
      out.write("&ref=");
      out.print(dto.getRef());
      out.write("&lev=");
      out.print(dto.getLev());
      out.write("&sunbun=");
      out.print(dto.getSunbun());
      out.write("\">답글쓰기</a></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</table>\r\n");
      out.write("			</fieldset>\r\n");
      out.write("		</article>\r\n");
      out.write("	</section>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!-- 하단으로 구분 -->\r\n");
      out.write("<footer>\r\n");
      out.write("	<hr>\r\n");
      out.write("	<div>Copyright &copy; SsangYong Corp. All Rights Reserved.</div>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
