/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.100
 * Generated at: 2025-03-13 07:46:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.phonebook;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class phonebookForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1740636672021L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1741836529848L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>250311</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/mainLayout.css\">\r\n");
request.setCharacterEncoding("UTF-8"); 
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');
      com.yong.member.MemberDAO mdao = null;
      mdao = (com.yong.member.MemberDAO) _jspx_page_context.getAttribute("mdao", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (mdao == null){
        mdao = new com.yong.member.MemberDAO();
        _jspx_page_context.setAttribute("mdao", mdao, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("\r\n");
      out.write("<!-- 상단으로 구분 -->\r\n");
      out.write("<script>\r\n");
      out.write("	function loginPopup() {\r\n");
      out.write("		window.open('/myweb/member/login.jsp', 'popup','width=400 ,height=150');\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");

String loginCheck = "로그인";
String joinCheck = "회원가입";

String id = (String) session.getAttribute("id");
if (id != null) {
	String name = mdao.getUserInfo(id);
	loginCheck = name + "님 로그인 중";
	joinCheck = "로그아웃";
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("	<div>\r\n");
      out.write("		<a ");
      out.print(id == null ? "onclick='loginPopup()'" : "");
      out.write('>');
      out.print(loginCheck);
      out.write("</a>| <a ");
      out.print(id == null ? " href='/myweb/member/memberJoin.jsp'" : "href='/myweb/member/logout.jsp'");
      out.write('>');
      out.print(joinCheck);
      out.write("</a>\r\n");
      out.write("	</div>\r\n");
      out.write("	<h1>JSP Study Site</h1>\r\n");
      out.write("	<!-- 메뉴 영역으로 구분 -->\r\n");
      out.write("	<nav>\r\n");
      out.write("		<ul>\r\n");
      out.write("			<li><a href=\"/myweb/index.jsp\">Home</a></li>\r\n");
      out.write("			<li><a href=\"/myweb/profile.jsp\">Profile</a></li>\r\n");
      out.write("			<li><a href=\"#\">자유게시판</a></li>\r\n");
      out.write("			<li><a href=\"#\">파일업로드</a></li>\r\n");
      out.write("			<li><a href=\"#\">방명록</a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</nav>\r\n");
      out.write("	<hr>\r\n");
      out.write("</header>");
      out.write("\r\n");
      out.write("	<section>\r\n");
      out.write("		<article>\r\n");
      out.write("			<h2>전화번호부 프로그램1</h2>\r\n");
      out.write("			<form name=\"phoneAdd1\" action=\"phoneAdd1_ok.jsp\">\r\n");
      out.write("				<fieldset>\r\n");
      out.write("					<legend>전화번호등록 part1</legend>\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><label>이름</label><input type=\"text\" name=\"name\"></li>\r\n");
      out.write("						<li><label>전화번호</label><input type=\"text\" name=\"tel\"></li>\r\n");
      out.write("						<li><label>주소</label><input type=\"text\" name=\"addr\"></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					<div>\r\n");
      out.write("						<input type=\"submit\" value=\"전화번호등록\"> <input type=\"reset\"\r\n");
      out.write("							value=\"다시작성\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</fieldset>\r\n");
      out.write("			</form>\r\n");
      out.write("		</article>\r\n");
      out.write("		<article>\r\n");
      out.write("			<h2>전화번호부 프로그램2</h2>\r\n");
      out.write("			<form name=\"phoneAdd2\" action=\"phoneAdd2_ok.jsp\">\r\n");
      out.write("				<fieldset>\r\n");
      out.write("					<legend>전화번호등록 part2</legend>\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><label>이름</label><input type=\"text\" name=\"name\"></li>\r\n");
      out.write("						<li><label>전화번호</label><input type=\"text\" name=\"tel\"></li>\r\n");
      out.write("						<li><label>주소</label><input type=\"text\" name=\"addr\"></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					<div>\r\n");
      out.write("						<input type=\"submit\" value=\"전화번호등록\"> <input type=\"reset\"\r\n");
      out.write("							value=\"다시작성\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</fieldset>\r\n");
      out.write("			</form>\r\n");
      out.write("		</article>\r\n");
      out.write("		<article>\r\n");
      out.write("			<h2>전화번호삭제 프로그램 1</h2>\r\n");
      out.write("			<form name=\"phoneDel1\" action=\"phoneDel1_ok.jsp\">\r\n");
      out.write("				<fieldset>\r\n");
      out.write("					<legend>전화번호 삭제 part1</legend>\r\n");
      out.write("					<table>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th>회원번호</th>\r\n");
      out.write("							<td><input type=\"text\" name=\"idx\"></td>\r\n");
      out.write("							<td><input type=\"submit\" value=\"회원번호 삭제\"></td>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</table>\r\n");
      out.write("				</fieldset>\r\n");
      out.write("			</form>\r\n");
      out.write("		</article>\r\n");
      out.write("		<article>\r\n");
      out.write("			<h2>전화번호삭제 프로그램 2</h2>\r\n");
      out.write("			<form name=\"phoneDel2\" action=\"phoneDel2_ok.jsp\">\r\n");
      out.write("				<fieldset>\r\n");
      out.write("					<legend>전화번호 삭제 part2</legend>\r\n");
      out.write("					<table>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th>회원번호</th>\r\n");
      out.write("							<td><input type=\"text\" name=\"idx\"></td>\r\n");
      out.write("							<td><input type=\"submit\" value=\"회원번호 삭제\"></td>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</table>\r\n");
      out.write("				</fieldset>\r\n");
      out.write("			</form>\r\n");
      out.write("		</article>\r\n");
      out.write("		<article>\r\n");
      out.write("			<fieldset>\r\n");
      out.write("				<legend>모든 전화번호 내역 part1</legend>\r\n");
      out.write("				<h3>\r\n");
      out.write("					<a href=\"phonebookList1.jsp\">모든 전화번호 내역보기 part1</a>\r\n");
      out.write("				</h3>\r\n");
      out.write("			</fieldset>\r\n");
      out.write("		</article>\r\n");
      out.write("		<article>\r\n");
      out.write("			<fieldset>\r\n");
      out.write("				<legend>모든 전화번호 내역 part2</legend>\r\n");
      out.write("				<h3>\r\n");
      out.write("					<a href=\"phonebookList2.jsp\">모든 전화번호 내역보기 part2</a>\r\n");
      out.write("				</h3>\r\n");
      out.write("			</fieldset>\r\n");
      out.write("		</article>\r\n");
      out.write("		<article>\r\n");
      out.write("			<h2>전화번호검색 프로그램 1</h2>\r\n");
      out.write("			<form name=\"phoneSearch1\" action=\"phoneSearch1_ok.jsp\">\r\n");
      out.write("				<fieldset>\r\n");
      out.write("					<legend>전화번호 검색 part1</legend>\r\n");
      out.write("					<table>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th>회원이름</th>\r\n");
      out.write("							<td><input type=\"text\" name=\"name\"></td>\r\n");
      out.write("							<td><input type=\"submit\" value=\"회원 검색\"></td>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</table>\r\n");
      out.write("				</fieldset>\r\n");
      out.write("			</form>\r\n");
      out.write("		</article>\r\n");
      out.write("		<article>\r\n");
      out.write("			<h2>전화번호검색 프로그램 2</h2>\r\n");
      out.write("			<form name=\"phoneSearch2\" action=\"phoneSearch2_ok.jsp\">\r\n");
      out.write("				<fieldset>\r\n");
      out.write("					<legend>전화번호 검색 part2</legend>\r\n");
      out.write("					<table>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th>회원이름</th>\r\n");
      out.write("							<td><input type=\"text\" name=\"name\"></td>\r\n");
      out.write("							<td><input type=\"submit\" value=\"회원 검색\"></td>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</table>\r\n");
      out.write("				</fieldset>\r\n");
      out.write("			</form>\r\n");
      out.write("		</article>\r\n");
      out.write("	</section>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!-- 하단으로 구분 -->\r\n");
      out.write("<footer>\r\n");
      out.write("	<hr>\r\n");
      out.write("	<div>Copyright &copy; SsangYong Corp. All Rights Reserved.</div>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
